# Once you push this code to a repo on GitHub, Dependabot will automatically start sending PRs to keep your dependencies up-to-date!
version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/script'
    schedule:
      interval: 'daily'

#  - package-ecosystem: "npm"
#    directory: "/apps/web"
#    schedule:
#      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/apps/api"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/apps/docs"
    schedule:
      interval: "daily"
