[package]
name = "osmon"
version = "0.1.0"
edition = "2018"
description = "A programming language for Uzbeks"
authors = ["UwUssimo Robinson <uwussimo@icloud.com>"]
keywords = ["language", "programming"]
readme = "readme.md"
categories = ["language"]
license = "Apache-2.0"

[dependencies]
bulut = { git = "https://github.com/osmon-lang/bulut" }
time = "0.1.40"
structopt = "0.2.13"
float_duration = "0.3.3"
