blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/uwussimo/osmon/discussions
    about: Ask questions and post ideas
  - name: 💭 Discord Server
    url: https://discord.gg/uwussimo
    about: Ask casual questions here
