[package]
name = "simple"
version = "0.1.0"
authors = ["UwUssimo Robinson <uwussimo@icloud.com>"]
edition = "2018"
description = "Library used for simple code generation for osmon"
license = "MIT"
keywords = ["codegen","vm"]

[dependencies]
osmon_vm = { path = "../../vm" }
mex = "0.1.0"